// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package immodels

import (
	"context"
	"time"

	"github.com/gookit/goutil/dump"
	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type chatLogModel interface {
	Insert(ctx context.Context, data *ChatLog) error
	FindOne(ctx context.Context, id string) (*ChatLog, error)
	Update(ctx context.Context, data *ChatLog) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	ListBySendTime(ctx context.Context, conversationId string, startSendTime, endSendTime, limit int64) ([]*ChatLog, error)
	ListByMsgIds(ctx context.Context, msgIds []string) ([]*ChatLog, error)
	UpdateMakeRead(ctx context.Context, id bson.ObjectID, readRecords []byte) error
}

type defaultChatLogModel struct {
	conn *mon.Model
}

func newDefaultChatLogModel(conn *mon.Model) *defaultChatLogModel {
	return &defaultChatLogModel{conn: conn}
}

func (m *defaultChatLogModel) Insert(ctx context.Context, data *ChatLog) error {
	//if data.ID.IsZero() {
	//	data.ID = bson.NewObjectID()
	//	data.CreateAt = time.Now()
	//	data.UpdateAt = time.Now()
	//}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultChatLogModel) FindOne(ctx context.Context, id string) (*ChatLog, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data ChatLog

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatLogModel) Update(ctx context.Context, data *ChatLog) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultChatLogModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}

// 查询聊天记录
func (m *defaultChatLogModel) ListBySendTime(ctx context.Context, conversationId string, startSendTime, endSendTime, limit int64) ([]*ChatLog, error) {

	var data []*ChatLog
	// 1. 构建原生 FindOptions
	opt := options.Find() // 原生构建器
	opt.SetSort(bson.M{"send_time": -1})
	// 设置 limit
	limitVal := DefaultChatLogLimit
	if limit > 0 {
		limitVal = limit
	}
	opt.SetLimit(limitVal)
	// 2. 构建查询条件
	filter := bson.M{"conversation_id": conversationId}
	// 根据不同的时间参数组合构建条件
	if startSendTime > 0 && endSendTime > 0 {
		// 同时提供开始和结束时间：查询时间范围内的记录
		filter["send_time"] = bson.M{
			"$gt":  startSendTime,
			"$lte": endSendTime,
		}
	} else if startSendTime > 0 {
		// 只提供开始时间：查询开始时间之后的记录（使用 $gt）
		filter["send_time"] = bson.M{
			"$gt": startSendTime,
		}
	} else if endSendTime > 0 {
		// 只提供结束时间：查询结束时间之前的记录
		filter["send_time"] = bson.M{
			"$lte": endSendTime,
		}
	}
	dump.P(filter)
	err := m.conn.Find(ctx, &data, filter, opt)
	switch err {
	case nil:
		return data, nil
	case mongo.ErrNoDocuments:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatLogModel) ListByMsgIds(ctx context.Context, msgIds []string) ([]*ChatLog, error) {
	var data []*ChatLog

	ids := make([]primitive.ObjectID, 0, len(msgIds))
	for _, msgId := range msgIds {
		oid, _ := primitive.ObjectIDFromHex(msgId)
		ids = append(ids, oid)
	}

	filter := bson.M{"_id": bson.M{"$in": ids}}
	err := m.conn.Find(ctx, &data, filter, nil)
	switch err {
	case nil:
		return data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatLogModel) UpdateMakeRead(ctx context.Context, id bson.ObjectID, readRecords []byte) error {
	_, err := m.conn.UpdateMany(ctx, bson.M{"_id": id}, bson.M{
		"readRecords": readRecords,
	})
	return err
}
