// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/HeRedBo/easy-chat/apps/im/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 根据消息ID获取已读未读记录
				Method:  http.MethodGet,
				Path:    "/chatlog/records",
				Handler: GetChatLogReadRecordsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/im"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 根据用户获取聊天记录
				Method:  http.MethodGet,
				Path:    "/chatlog",
				Handler: getChatLogHandler(serverCtx),
			},
			{
				// 验证消息已读记录查询
				Method:  http.MethodGet,
				Path:    "/chatlog/readRecords",
				Handler: GetChatLogReadRecordsHandler(serverCtx),
			},
			{
				// 获取会话
				Method:  http.MethodGet,
				Path:    "/conversation",
				Handler: getConversationsHandler(serverCtx),
			},
			{
				// 更新会话
				Method:  http.MethodPut,
				Path:    "/conversation",
				Handler: putConversationsHandler(serverCtx),
			},
			{
				// 建立会话
				Method:  http.MethodPost,
				Path:    "/setup/conversation",
				Handler: setUpUserConversationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/im"),
	)
}
