FROM alpine:3.18

ARG SERVER_NAME
ARG SERVER_TYPE
ARG PORT=

# 将构建参数转为环境变量，使运行时可用
ENV PORT=${PORT}

RUN echo -e "https://mirrors.aliyun.com/alpine/v3.18/main\nhttps://mirrors.aliyun.com/alpine/v3.18/community/" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone
ENV TZ=Asia/Shanghai



ENV BIN_DIR=/${SERVER_NAME}/bin
ENV CONF_DIR=/${SERVER_NAME}/conf
ENV BIN_FILE=${BIN_DIR}/${SERVER_NAME}-${SERVER_TYPE}
ENV CONF_FILE=${CONF_DIR}/${SERVER_NAME}.yaml

RUN mkdir -p ${BIN_DIR} ${CONF_DIR}
WORKDIR /${SERVER_NAME}

COPY ./bin/${SERVER_NAME}-${SERVER_TYPE} ${BIN_FILE}
COPY ./apps/${SERVER_NAME}/${SERVER_TYPE}/etc/dev/${SERVER_NAME}.yaml ${CONF_FILE}

RUN chmod +x ${BIN_FILE}

HEALTHCHECK --interval=5s --timeout=2s --retries=3 \
    CMD if [ -z "$PORT" ]; then exit 0; else netstat -tlpn | grep -q ":$PORT " || exit 1; fi

ENTRYPOINT ["/bin/sh", "-c", "exec ${BIN_FILE} -f ${CONF_FILE}"]