FROM alpine:3.18

# 添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.18/main\nhttps://mirrors.aliyun.com/alpine/v3.18/community/" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone
ENV TZ=Asia/Shanghai

ARG SERVER_NAME=user
ARG SERVER_TYPE=api

# 定义绝对路径 
ENV BIN_DIR=/${SERVER_NAME}/bin
ENV CONF_DIR=/${SERVER_NAME}/conf
ENV BIN_FILE=${BIN_DIR}/${SERVER_NAME}-${SERVER_TYPE}
ENV CONF_FILE=${CONF_DIR}/${SERVER_NAME}.yaml



# 目录 
# 这个关键词的意思是复制的意思，可以将宿主机中的内容复制到容器中
# 命令 左边是宿主机的目录，右边是容器目录
RUN mkdir -p /${SERVER_NAME}/bin /${SERVER_NAME}/conf

# 进入容器
WORKDIR /${SERVER_NAME}

# ========================
# 直接拷贝本地编译好的文件
# ========================
COPY ./bin/${SERVER_NAME}-${SERVER_TYPE} ${BIN_FILE}
COPY ./apps/${SERVER_NAME}/${SERVER_TYPE}/etc/dev/${SERVER_NAME}.yaml ${CONF_FILE}

# 配置文件
COPY ./apps/${SERVER_NAME}/${SERVER_TYPE}/etc/dev/${SERVER_NAME}.yaml /${SERVER_NAME}/conf/

# 为二进制提供执行权限
RUN chmod +x ${BIN_FILE}
# 健康检查（判断服务是否真正就绪）
HEALTHCHECK --interval=5s --timeout=2s --retries=3 \
    CMD netstat -tuln | grep 8888 || exit 1
# 启动
# windows 下需要指定配置文件
# ENTRYPOINT ["/user/bin/user-rpc", "-f", "/user/conf/user.yaml"]
# 替换成这个：让容器一直活着，你可以进去操作
# CMD ["sleep", "infinity"]
ENTRYPOINT ["/user/bin/user-api", "-f", "/user/conf/user.yaml"]
# ENTRYPOINT ${RUN_BIN} -f ${RUN_CONF}
